### ISSUE TITLE
symbol lookup error: /app/vendor/bundle/gems/puma-3.6.0/lib/puma/puma_http11.so: undefined symbol: rb_data_object_alloc

### ISSUE THREAD

**Issue by pywebdesign** [puma/puma#1130]
### Steps to reproduce

1) Using puma with docker in dev

```
# Dockerfile
FROM rails:4.2
RUN mkdir /app
RUN mkdir /app/vendor
RUN mkdir /app/vendor/bundle
WORKDIR /app
ADD ./bundle.config /root/.bundle/config

RUN apt-get update -y && apt-get install -y nodejs && apt-get install -y npm
RUN npm install -g bower
RUN npm cache clean -f && npm install -g n && n stable
RUN echo "{ \"allow_root\": true,   \"interactive\": false }" > /root/.bowerrc
```

```
#docker-compose.yml
files:
  image: ubuntu
  volumes:
    - ./vendor:/app/vendor
    - ./dbdata:/var/lib/postgresql/data/

db:  
  image: "pywebdesign/postgis"
  volumes_from:
    - files

web:  
  build: .
  command: bundle exec rails server -b 0.0.0.0
  environment:
    - BUNDLE_PATH=vendor/bundle
  volumes:
    - .:/app
  volumes_from:
    - files
  ports:
    - "3000:3000"
  links:
    - db
    - files
```

### Expected behavior

It should serve when docker-compose up like with version 3.5.2

### Actual behavior

web_1    | Puma starting in single mode...
web_1    | * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
web_1    | * Min threads: 0, max threads: 16
web_1    | * Environment: development
web_1    | * Listening on tcp://0.0.0.0:3000
web_1    | Use Ctrl-C to stop
web_1    | puma 3.6.0 (tcp://0.0.0.0:3000) [app]: symbol lookup error: /app/vendor/bundle/gems/puma-3.6.0/lib/puma/puma_http11.so: undefined symbol: rb_data_object_alloc

### System configuration

**Ruby version**: 2.3.1-p112
**Rails version**: 4.2
