### ISSUE TITLE
Rails API using Docker doesn't return any responses...

### ISSUE THREAD

**Issue by sungsong88** [puma/puma#1539]
### Steps to reproduce

1) Using docker compose, start up RailsAPI service, Nginx service

2) For Rails API service, i run commend (using docker-compose)
```yaml
development_api:
    environment:
      - RAILS_ENV=development
      - WEB_HOST=http://dockerhost:1000/
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    image: mycompany/rails-api
    command: ["rails", "server","-b","0.0.0.0","-P","tmp/pids/development.pid"]
    volumes:
      - ./rails-api:/usr/src/rails-api
    ports:
      - 3000:3000
    links:
      - postgres
      - redis
```

3) So, now rails server using puma is up!

4) **http://dockerhost:3000/check_version** XHR is fired from client side. Response is empty.

5) **ws://dockerhost:3000/cable** WebSocket connection attempted from client side. Works!

### Expected behavior

XHR should return some responses!

### Actual behavior

XHR response body is empty...

### System configuration

**Ruby 2.5**:
**Rails 5.1.5**:
**Puma latest(3.11.3)**:

### Additional Attachment
XHR information
![image](https://user-images.githubusercontent.com/4941095/37615964-e1fea86e-2b84-11e8-8988-a42953345c4f.png)

### Additional Comment
I used to use 'thin' for my server, and for 'thin' server it was opposite. XHR was working, but WebSocket wasn't working.
