### ISSUE TITLE
before_fork Proc is written to puma.state file

### ISSUE THREAD

**Issue by manno** [puma/puma#830]
I'm running `pumactl -S tmp/pids/puma.state restart` and it fails with `allocator undefined for Proc`.

The state file contains this line:

```yaml
---
pid: 12356
config: !ruby/object:Puma::Configuration
  options:
    :mode: :http
    :before_fork:
    - !ruby/object:Proc {}
```

It works with the `on_restart` block, so I guess `before_fork` should be deleted from options, too. `on_restart` is removed here: https://github.com/puma/puma/blob/master/lib/puma/cli.rb#L115
